### ISSUE TITLE
Won't install on M1 Mac mini

### ISSUE THREAD

**Issue by martindinicolino** [sebj/homebridge-mac-temperature-light#7]
I'm having trouble with installing this plugin on my M1 Mac mini, I won't exclude user error - actually that's the most likely cause as I'm a total newbie. Still, I'm willing to learn and any help would be appreciated.

at some point during the installation I get this:

...
CXX(target) Release/obj.target/Light/src/Light.o
../src/Light.mm:27:30: error: no matching member function for call to 'Set'
                valuesArray->Set(0, Number::New(isolate, values[0]));
...
../src/Light.mm:28:30: error: no matching member function for call to 'Set'
                valuesArray->Set(1, Number::New(isolate, values[0]));
...
2 errors generated.
make: *** [Release/obj.target/Light/src/Light.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
gyp ERR! System Darwin 20.4.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/homebridge-mac-temperature-light
gyp ERR! node -v v14.16.1
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! homebridge-mac-temperature-light@1.1.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the homebridge-mac-temperature-light@1.1.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
...
Command failed. Please review log for details.

**Comment by martindinicolino** [comment]
Hi,
does anybody have an idea in how to fix this?
